name: Deploy Laravel to Local Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /var/www/ukl
          git pull origin main

      - name: Install dependencies
        run: |
          cd /var/www/ukl
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Laravel optimize & migrate
        run: |
          cd /var/www/ukl
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
