name: Deploy Laravel (Build and Deploy)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Backup .env
        run: |
          cp /var/www/UKL/.env /home/siswa/temp/.env.backup

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build in home user
        run: |
          mkdir -p /home/siswa/build/UKL
          rsync -a --delete ./ /home/siswa/build/UKL
          cd /home/siswa/build/UKL
          composer update
          composer install

      - name: Deploy to web root
        run: |
          rsync -a --delete \
            --no-owner --no-group \
            /home/siswa/build/UKL/ /var/www/UKL/

      - name: Laravel optimize & migrate
        run: |
          mv /home/siswa/temp/.env.backup /var/www/UKL/.env
          cd /var/www/UKL
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

